version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    groups:
      rust-dependencies:
        patterns:
        - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    groups:
      github-actions:
        patterns:
        - "*"
